### PR TITLE
Update tree.png

### PR DESCRIPTION
**Pull request by toadettexmushina**
Replace tree icon with the wotw map icon version

### CODE REVIEW

**Comment by Mawex** [comment]
The visual style doesn't really fit
grafik

**Comment by toadettexmushina** [comment]
Darn, you might be right. As much as I like the wotw one because it actually looks like a tree (or the spirit willow), it doesn't gel as well with the skill icons. I could try beefing it up a bit or matching the hue a little better tho.

**Comment by MunWolf** [comment]
Probably if you make it less sharp, add some blue glow on the edges it might mesh better.

**Comment by timoschwarzer** [comment]
gonna chop this tree

**Comment by Mawex** [comment]
trees have been changed: e6f6b3d3d3308917d330cb688bf156ad7d7e0db9

**Pull request closed without merging**
